// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhjqgrftsozfmidoqkcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoanFncmZ0c296Zm1pZG9xa2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODg5MjAsImV4cCI6MjA2Mzg2NDkyMH0.WLFF4I-fDcRM3R7fiFKxS1QND750BfxcI9P0yoqvdis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);